# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oaT_eH2U8FK0OKzqQjVMfDFtNu5klL8O
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Calculadora Panadería Artesanal 🍞📊", layout="centered")

# Título de la app
st.title("Calculadora de Punto de Equilibrio 🧮🍞")
st.markdown("Esta aplicación te ayudará a conocer cuándo tu panadería artesanal comienza a generar ganancias 💰✨.")

# Entradas del usuario
st.sidebar.header("🔧 Datos del negocio")
costo_fijo = st.sidebar.number_input("Costo fijo mensual (COP)", min_value=0, value=500000, step=10000)
costo_variable = st.sidebar.number_input("Costo variable por unidad (COP)", min_value=0, value=1000, step=100)
precio_venta = st.sidebar.number_input("Precio de venta por unidad (COP)", min_value=1, value=2000, step=100)

# Validación
if precio_venta <= costo_variable:
    st.error("⚠️ El precio de venta debe ser mayor al costo variable para que haya ganancia.")
else:
    # Cálculo del punto de equilibrio
    punto_equilibrio = costo_fijo / (precio_venta - costo_variable)
    punto_equilibrio = round(punto_equilibrio)

    st.success(f"📈 Tu panadería artesanal debe vender al menos **{punto_equilibrio} panes** al mes para alcanzar el punto de equilibrio.")

    # Simulación de ingresos y costos
    unidades = list(range(0, punto_equilibrio * 2 + 50, 50))
    ingresos = [precio_venta * u for u in unidades]
    costos_totales = [costo_fijo + (costo_variable * u) for u in unidades]
    utilidad = [i - c for i, c in zip(ingresos, costos_totales)]

    df = pd.DataFrame({
        "Unidades Vendidas": unidades,
        "Ingresos (COP)": ingresos,
        "Costos Totales (COP)": costos_totales,
        "Utilidad (COP)": utilidad
    })

    # Mostrar gráfico 📊
    st.subheader("Gráfico de Ingresos vs Costos Totales 📉📈")
    fig, ax = plt.subplots()
    ax.plot(unidades, ingresos, label="Ingresos", color="green")
    ax.plot(unidades, costos_totales, label="Costos Totales", color="red")
    ax.axvline(punto_equilibrio, linestyle="--", color="blue", label=f"Punto de equilibrio: {punto_equilibrio} unidades")
    ax.set_xlabel("Unidades vendidas")
    ax.set_ylabel("Valor en COP")
    ax.legend()
    ax.grid(True)
    st.pyplot(fig)

    # Mostrar tabla
    st.subheader("📋 Tabla de resultados")
    st.dataframe(df)

    # Explicación final
    st.info

